### ISSUE TITLE
Cleartext HTTP traffic to fast.player.liquidplatform.com not permitted

### ISSUE THREAD

**Issue by renatacmn** [sambatech/player_sdk_android#69]
Sample app doesn't work on Android 9.0. It gives the error:

```
java.io.IOException: Cleartext HTTP traffic to fast.player.liquidplatform.com not permitted
        at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:467)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:416)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
        at java.net.URL.openStream(URL.java:1073)
        at com.sambatech.player.SambaApi$RequestMediaTask.doInBackground(SambaApi.java:155)
        at com.sambatech.player.SambaApi$RequestMediaTask.doInBackground(SambaApi.java:133)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

I've had this error in other projects and the solution was to add the line `android:usesCleartextTraffic="true"` to the application tag on AndroidManifest, but I tried to do this in the sample code and it didn't work.

**Comment by affbedran** [comment]
Is this issue solved, @renatacmn? If so, how did you do it?

**Comment by renatacmn** [comment]
@affbedran Not yet. I just re-downloaded the sample project and it runs, but doesn't play any video. The error is the same.
